parameters:
#    curso_security.example.class: Curso\SecurityBundle\Example

services:
#    curso_security.example:
#        class: %curso_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
